Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "forwarded_port", guest: 22, host: 2222

  config.vm.synced_folder "F:/scripts/shellscripts", "/home/vagrant/shellscripts"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end
end
